---
title: "Crabs tutorial"
author: "Caleb Collins"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Step 1 download R package from Github

```{r} 
devtools::install_github("calebcollins/crabs.pkg")
library(collins.pkg)
```
Step 2, Download the crabs data set from googlesheets

```{r}
library(googlesheets4)
googlesheets4::gs4_deauth()
crabs <- read_sheet("https://docs.google.com/spreadsheets/d/14LA9eB3CEgEosqUwT7zkhjfiNsGt6zKu9BU9xAx3BUo/edit?usp=sharing")
```



Now we will clean the data set by removing na's will stop if no N/As are found 

```{r, eval=FALSE}
clean_data(crabs)
```


Now we will mutate the data. Sorting it by a chosen column
```{r, eval=FALSE}
mutate_data(crabs, "hindfoot_lenght")

mutate_data(crabs,"rear_width")
```

Now we will make a graph with two columns 
```{r} 
function_graph(crabs, rear_width, body_depth)
function_graph(crabs, sex, color)
```

Next we will perform an linear model analysis

```{r}
lm_function(crabs, "rear_width", "body_depth")
```

```{r,eval=FALSE}
lm_function(crabs, "rear_width", "hindfoot_length")
```

Last we will kill the data because i did it on accident 
```{r} 
fun_function(crabs)
```